### ISSUE TITLE
Code conflict by interpret the "_" character ,  need to be fixed

### ISSUE THREAD

**Issue by gaofenghua** [gaofenghua/LodestoneEx#1]
string classFullName = string.Empty;
                            if (2 == sectionName.Split('_').Length & false) //This conflict need to be fixed -- Indy
                            {
                                classFullName = assemblyName + ".Jobs." + sectionName.Split('_')[0] + ".Config";
                            }
                            else
                            {
                                classFullName = assemblyName + ".Jobs." + sectionName + ".Config";
                            }

**Comment by jiangnaifu** [comment]
Fixed by replacing '_' with '-', please check updates for detail.
